@startuml woda-uml
left to right direction

package Units {
    enum BattleUnitType {
        PatrolBoat,
        Interceptor,
        Cruiser,
        Dreadnought,
    }

    enum BattleUnitCategory {
        Land,
        Marine,
        Aerial,
    }

    abstract class BattleUnit {
        # unsigned int segments;
        - unsigned int destroyedSegments = 0;
        - BattleUnitCategory category;

        + BattleUnit();
        + virtual ~BattleUnit() = default;
        + virtual BattleUnitType GetType() const = 0;
        + BattleUnitCategory GetCategory();
        + void DestroySegment();
        + bool IsDestroyed() const;
    }

    ' Size: 1
    class PatrolBoat {
        + PatrolBoat();
        + BattleUnitType GetType() const override;
    }

    ' Size: 2 
    class Interceptor {
        + Interceptor();
        + BattleUnitType GetType() const override;
    }

    ' Size: 3
    class Cruiser {
        + Cruiser();
        + BattleUnitType GetType() const override;
    }

    ' Size: 4
    class Dreadnought {
        + Dreadnought();
        + BattleUnitType GetType() const override;
    }

    BattleUnit --> BattleUnitType
    BattleUnit --> BattleUnitCategory

    BattleUnit <|-- PatrolBoat
    BattleUnit <|-- Interceptor
    BattleUnit <|-- Cruiser
    BattleUnit <|-- Dreadnought
}

package Boards {
    class SegmentBoard <<template <size_t WIDTH, size_t HEIGHT>>> {
        - array<array<bool, HEIGHT>, WIDTH> segments;

        + SegmentBoard();
        + const array<array<bool, HEIGHT>, WIDTH>& Segments() const;
        + virtual bool ToggleSegment(size_t x, size_t y);
        + void Clear();
    }

    class ExtendedSegmentBoard {
        + ExtendedSegmentBoard();
        + bool ToggleSegment(size_t x, size_t y) override;
    }

    SegmentBoard <|-- ExtendedSegmentBoard

    class GameBoard <<template <size_t WIDTH, size_t HEIGHT>>> {
        - SegmentBoard<WIDTH, HEIGHT> segments;
        - array<array<shared_ptr<BattleUnit>, HEIGHT>, WIDTH> units;

        + GameBoard();
        + ~GameBoard();
        + const SegmentBoard<WIDTH, HEIGHT>& Segments() const;
        + const array<array<shared_ptr<BattleUnit>, HEIGHT>, WIDTH>& Units() const;
        + void ParseSegments();
        + bool FireAt(size_t x, size_t y);
        + void FixSegment(size_t x, size_t y);
        + bool IsGameOver();
    }

    GameBoard *-- BattleUnit
    GameBoard *-- SegmentBoard
}

package Profile {
    struct Statistics {
        chrono::seconds fastestWonGame = 0;
        chrono::seconds totalPlaytime = 0;
        unsigned int longestHitStreak = 0;
        unsigned int gamesPlayed = 0;
        unsigned int gamesWon = 0;
        unsinged int gamesLost = 0;
        unsigned int highestScore = 0;
        unsigned int totalShotsFired = 0;
        unsigned int totalShotsHit = 0;
        unsigned int totalUnitsDestroyed = 0;
    }

    ' TODO: Add more unlocks
    enum UnlockableContent <<flags>> {
        None = 0,
        MediumComputer = 1,
        HardComputer = 2,
        SalvoMode = 4,
        ExtendedMode = 8,
    }

    struct Achievement {
        string name;
        string description;
        UnlockableContent content;
        bool unlocked;
    }

    ' Look up CRTP for Clone() implementation
    interface IClone <<template <class Derived>>> {
        + IClone() = default;
        + ~IClone() = default;
        + unique_ptr<Derived> Clone();
    }

    ' Implements Prototype design pattern
    class AchievementPool {
        - unordered_map<string, Achievement> NameToAchievementMap;

        + AchievementPool();
        + const Achievement& Achievement(string name) const;
        + bool Unlock(string name);
    }

    AchievementPool --|> IClone
    AchievementPool *-- Achievement

    enum Color {}
    enum BorderPattern {}
    enum UnitPattern {}

    struct UserSettings {
        Color unitColor;
        Color boardColor;
        Color borderColor;
        BorderPattern borderPattern;
        UnitPattern unitPattern;
        bool autoMarkEmptyFields;
    }

    UserSettings --> Color
    UserSettings --> BorderPattern
    UserSettings --> UnitPattern

    class UserProfile {
        + size_t id;
        + string name;
        + Statistics statistics;
        + unique_ptr<AchievementPool> achievements;
        + uint64_t unlockedContent;
        + UserSettings settings;

        + UserProfile(string name);
        + UserProfile(...);
        + ~UserProfile();
    }

    UserProfile *-- Statistics
    UserProfile *-- AchievementPool
    UserProfile --> UnlockableContent
    UserProfile *-- UserSettings
}

' TODO: Adapt computer/player interface for frontend
package Computers {
    enum ComputerType {
        Easy,
        Medium,
        Hard,
    }

    class Computer {
        + ComputerType type;
        + GameBoard board;

        + Computer(ComputerType type);
        + void MakeMove();
    }

    Computer -> ComputerType
    Computer *-- GameBoard
}

package Game {
    struct Player {
        UserProfile& profile;
        GameBoard board;
        unsigned int hitStreak = 0;
        unsigned int longestHitStreak = 0;
        unsigned int score = 0;
        unsigned int shotsFired = 0;
        unsigned int shotsHit = 0;
        unsigned int unitsDestroyed = 0;
    }

    Player *.. UserProfile
    Player *-- GameBoard

    ' Implements Command design pattern
    interface ICommand {
        + virtual ~ICommand() = default;
        + virtual bool execute() = 0;
        + virtual void undo() = 0;
    }

    struct Coordinates {
        size_t x;
        size_t y;
    }

    class FireCommand {
        - GameBoard& board;
        - Coordinates coords;

        + FireCommand(GameBoard& board, Coordinates coords);
        + bool execute() override;
        + void undo() override;
    }

    FireCommand --> Coordinates
    FireCommand --|> ICommand

    class SalvoFireCommand {
        - GameBoard& board;
        - vector<Coordinates> coords;

        + SalvoFireCommand(GameBoard& board, vector<Coordinates> coords);
        + bool execute() override;
        + void undo() override;
    }

    SalvoFireCommand --> Coordinates
    SalvoFireCommand --|> ICommand

    enum FireCommandType {
        FireCommand,
        SalvoFireCommand,
    }

    struct GameMode {
        string name;
        string description;
        size_t boardWidth;
        size_t boardHeight;
        bool isExtended;
        FireCommandType commandType;
        unordered_map<UnitType, size_t> unitPool;
    }

    GameMode -> FireCommandType

    enum GameState {
        Started,
        Setting,
        Playing,
        Over,
    }

    class GameManager {
        - unsigned int id;
        - GameMode mode;
        - GameState state;
        - vector<Player> players;
        - vector<Computers> computers;
        - vector<unsigned int> turnList;
        - unsigned int currentTurn;
        - vector<unique_ptr<ICommand>> history;
        - chrono::seconds playtime;

        + GameManager(GameMode mode, vector<UserProfile&> profiles,
        vector<ComputerType> computers, vector<unsigned int> turnList);
        + ~GameManager();
        + GameMode Mode() const;
        + const vector<Player> Players() const;
        + vector<unsigned int> TurnList() const;
        + unsigned int CurrentTurn() const;
        + void SetBoards();
        + void StartGame();
        + bool ExecuteCommand(unique_ptr<ICommand> command);
        + void HandleGameOver();
        + Replay GetReplay();
    }

    GameManager --> GameMode
    GameManager --> GameState
    GameManager *-- Player
    GameManager *-- Computer
    GameManager --> ICommand
}

package Replays {
    struct Replay {
        unsigned int id;
        vector<Player> players;
        vector<unique_ptr<ICommand>> history;
        unsigned int winnerId;
        chrono::seconds playtime;
        time_t timestamp;
    }

    Replay <.. GameManager

    ' Implements Singleton design pattern
    class ReplayManager {
        - {static} ReplayManager instance;
        - vector<Replay> replays;

        - ReplayManager();
        + {static} ReplayManager GetInstance();
        + ~ReplayManager();
        + const vector<Replay>& Replays() const;
        + void SaveReplay(Replay replay);
        + bool Play(size_t replayId);
        + bool Analyze(size_t replayId);
    }

    ReplayManager *-- Replay
}

@enduml
