name: validate-style
on: 
  push:
jobs:
  validate-using-clang-format:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v5
      - name: Install clang-format
        run: |
          if ! command -v clang-format-20 >/dev/null 2>&1
          then
            echo "clang-format-20 could not be found, installing..."
            sudo apt add-repository -y "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-20 main"
            sudo apt update && sudo apt install clang-format-20
          else
            echo "clang-format-20 is already installed."
          fi
      - name: Validate code style
        run: |
          FILES=$(find src/ -name '*.cpp' -o -name '*.hpp' -o -name '*.h')
          for file in $FILES; do
            clang-format-20 -style=file "$file" | diff "$file" - || { echo "Code style issues found in $file"; exit 1; }
          done
          echo "All files conform to the code style." 
  validate-using-clang-tidy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}
      - name: Install clang-tidy
        run: |
          if ! command -v clang-tidy-20 >/dev/null 2>&1
          then
            echo "clang-tidy-20 could not be found, installing..."
            sudo apt add-repository -y "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-20 main"
            sudo apt update && sudo apt install clang-tidy-20
          else
            echo "clang-tidy-20 is already installed."
          fi
      - name: Configure CMake
        run: cmake .
      - name: Validate code style
        run: |
          if ${{ github.event_name == 'pull_request' }}; then
            tst=`git diff -r HEAD^1 HEAD -U0 --no-color --name-only | egrep ".*\.((cpp)|(h))$"`
          elif [ "${{ github.event.before != '0000000000000000000000000000000000000000' }} ]; then
            tst=`git diff ${{ github.event.before }} ${{ github.event.after }} -U0 --no-color --name-only | egrep ".*\.((cpp)|(h))$"`
          else
            tst=`find src/ -name '*.cpp' -o -name '*.hpp' -o -name '*.h'`
          fi
          clang-tidy-20 --warnings-as-errors \* -p . $tst || { echo "Found code style issues"; exit 1; }
          echo "All files conform to the code style." 

  
